### ISSUE TITLE
Polish Requests

### ISSUE THREAD

**Issue by mikemilla** [jacob-craffey/choice-mobile-test-app#1]
Hey, could you make these changes to the app?

- [x] Ensure the navigation pop gesture works on iOS (Looks like the CustomPageRoute disabled it. The custom transition is cool, we just want to make sure iOS users can still swipe to go back from the detail page. Resources: https://drive.google.com/file/d/1dJbQpCpNy0ILPvAlQ5sXyqBEoVj1ZRV9/view?usp=sharing & https://docs.flutter.dev/cookbook/navigation/navigation-basics#interactive-example
- [x] Match AppBar shadow to the design
- [x] Match ListView padding to the design (looks like the top padding isn't accurate. You can use padding on the ListView itself btw: https://stackoverflow.com/a/59978660/2415921](https://stackoverflow.com/a/59978660/2415921)
- [x] Prevent full loading screen from showing when user is performing a "pull to refresh" (try doing a pull to refresh in Instagram for an example)
- [x] Make sure `Error` handles safe areas. (For reference: https://api.flutter.dev/flutter/widgets/SafeArea-class.html)
- [x] Make sure `PostDetail` scroll view content uses safe areas as well. (Don't clip the content at the bottom edge though. Just make sure there is padding in the scroll view)
- [x] Scroll bar styles are overridden from what user expect on each platform. Can you revert that to default settings?
- [x] Can you move `maxWidth` for the pages to a global constant?

Also, just a heads up that you can measure inside Figma pretty easily. Here is how to do it:
https://help.figma.com/hc/en-us/articles/360039956974-Measure-distances-between-layers

**Comment by jacob-craffey** [comment]
All taken care of!

Just a heads up, there were some issues with gesture support with my custom page navigation. An alternative solution I implemented was adding the default iOS `CupertinoPageTransition` to all platforms (macOS, iOS, windows, android) via `PageTransitionsTheme` in the `main.dart` file.

Let me know if you have any questions about any of the changes I've made
